# Generated by Django 3.2.2 on 2022-01-17 06:14

import books.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Not known', max_length=128, verbose_name='Yozuvchining ismi va familiyasi:')),
                ('date_birth', models.DateField(verbose_name="Yozuvchining tug'ilgan sanasi:")),
                ('date_death', models.DateField(blank=True, null=True, verbose_name='Yozuvchining vafot etgan sanasi:')),
            ],
            options={
                'verbose_name': 'Kitob muallifi:',
                'verbose_name_plural': 'Kitob mualliflari:',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='Kitob raqami:')),
                ('book_title', models.CharField(max_length=128, verbose_name='Kitobning nomi:')),
                ('published_year', models.DateField(verbose_name='Kitob nashr qilingan sana:')),
            ],
            options={
                'verbose_name': 'Kitob:',
                'verbose_name_plural': 'Kitoblar',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=128, verbose_name='Kutubxina numi:')),
                ('address', models.CharField(max_length=255, verbose_name='Kutubxona manzili:')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=books.models.book_image_path, verbose_name='Rasmi:')),
                ('video', models.FileField(blank=True, null=True, upload_to=books.models.book_video_path, verbose_name='Videosi:')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kutubhona haqida batafsil:')),
            ],
            options={
                'verbose_name': 'Kutubxona:',
                'verbose_name_plural': 'Kutubxonalar:',
            },
        ),
        migrations.CreateModel(
            name='LiteratureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Asar janri:')),
            ],
            options={
                'verbose_name': 'Asar janri:',
                'verbose_name_plural': 'Asar janrlari',
            },
        ),
        migrations.CreateModel(
            name='LoanedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_loaned', models.DateField(verbose_name='Kitob olingan sana:')),
                ('date_due', models.DateField(verbose_name="Kitob qaytarilishi kerak bo'lgan sana:")),
                ('date_returned', models.DateField(blank=True, null=True, verbose_name='Kitob qaytarilgan sana:')),
                ('loan_status', models.TextField(choices=[('Vaqtida qaytarildi!', 'Vaqtida qaytarildi!'), ('Kechiktirib qaytarildi', 'Kechiktirib qaytarildi'), ('Hali qaytarilmadi!', 'Hali qaytarilmadi!')], default='Hali qaytarilmadi!', verbose_name='Kitob qaytarildimi:')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Kitob nomi:')),
            ],
            options={
                'verbose_name': 'Ijaraga olingan kitob:',
                'verbose_name_plural': 'Ijaraga olingan kitoblar:',
            },
        ),
    ]
