# Generated by Django 3.2.2 on 2022-01-17 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanedbook',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kitob oluvchi:'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='books.Author', verbose_name='Kitob muallifi:'),
        ),
        migrations.AddField(
            model_name='book',
            name='literature_category_id',
            field=models.ManyToManyField(to='books.LiteratureCategory', verbose_name='Adabiy janrlar:'),
        ),
    ]
